[package]
name = "v6prac"
version = "1.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.0.0"
femtovg = "0.3.3"
glutin = "0.28.0"